kinescope/cinema/urls.py
from django.urls import path
from . import views


app_name = 'cinema'

urlpatterns = [
    path('', views.index, name='index'),
    path('movies/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'sessions/<int:session_id>/',
        views.session_detail,
        name='session_detail'
    ),
    path('sessions/', views.session_list, name='session_list'),
    path('tickets/<int:session_id>/', views.tickets, name='tickets'),
    path('tickets/<int:session_id>/buy/', views.buy_ticket, name='buy_ticket'),
]

kinescope/kinescope/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_failure'

urlpatterns = [
    path('', include('cinema.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kinescope/pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),
    path('rules/', views.RulesView.as_view(), name='rules'),
]

kinescope/cinema/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from datetime import datetime as dt


User = get_user_model()


class Genre(models.Model):
    title = models.CharField(
        unique=True,
        max_length=128,
        verbose_name='Название'
    )

    class Meta:
        verbose_name = 'жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.title


class Hall(models.Model):
    title = models.CharField(
        max_length=64,
        verbose_name='Название/номер'
    )
    seats_quantity = models.IntegerField(
        validators=[MinValueValidator(10)],
        verbose_name='Количество мест',
        help_text='Мест должно быть не менее 10'
    )

    class Meta:
        verbose_name = 'зал'
        verbose_name_plural = 'Залы'

    def __str__(self):
        return self.title


class Seat(models.Model):
    number = models.CharField(
        max_length=10,
        verbose_name='Номер'
    )
    hall = models.ForeignKey(
        Hall,
        on_delete=models.CASCADE,
        related_name='seats',
        verbose_name='Зал'
    )

    class Meta:
        verbose_name = 'место'
        verbose_name_plural = 'Места'

    def __str__(self):
        return f'{self.hall.title} зал-{self.number}'


class Movie(models.Model):
    title = models.CharField(
        max_length=128,
        verbose_name='Название'
    )
    genre = models.ForeignKey(
        Genre,
        on_delete=models.RESTRICT,
        related_name='movies',
        verbose_name='Жанр'
    )
    duration = models.TimeField(
        verbose_name='Продолжительность',
        default='01:00'
    )
    description = models.CharField(
        max_length=512,
        verbose_name='Описание'
    )
    poster = models.ImageField(
        upload_to='posters',
        verbose_name='Постер'
    )
    is_in_the_cinema = models.BooleanField(
        verbose_name='В прокате',
        default=True
    )

    class Meta:
        verbose_name = 'фильм'
        verbose_name_plural = 'Фильмы'

    def __str__(self):
        return self.title


class Session(models.Model):
    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE,
        related_name='sessions',
        verbose_name='Фильм'
    )
    hall = models.ForeignKey(
        Hall,
        on_delete=models.CASCADE,
        related_name='sessions',
        verbose_name='Зал'
    )
    datetime = models.DateTimeField(
        verbose_name='Дата и время'
    )
    seats = models.ManyToManyField(
        Seat,
        through='SeatForSession'
    )

    class Meta:
        verbose_name = 'сеанс'
        verbose_name_plural = 'Сеансы'
        ordering = ('datetime',)

    def __str__(self):
        return self.movie.title + ' - ' \
              + self.datetime.strftime('%d.%m.%Y %H:%M')


class SeatForSession(models.Model):
    session = models.ForeignKey(
        Session,
        on_delete=models.CASCADE,
        related_name='seats_for_session',
        verbose_name='Сеанс'
    )
    seat = models.ForeignKey(
        Seat,
        on_delete=models.CASCADE,
        related_name='sessions',
        verbose_name='Место'
    )
    is_taken = models.BooleanField(
        verbose_name='Занято'
    )

    class Meta:
        verbose_name = 'место на сеанс'
        verbose_name_plural = 'Места на сеанс'

    def __str__(self):
        return f'{self.seat.number}'


class Ticket(models.Model):
    seat_for_session = models.ForeignKey(
        SeatForSession,
        on_delete=models.CASCADE,
        related_name='tickets',
        verbose_name='Место на сеанс'
    )
    customer = models.ForeignKey(
        User,
        on_delete=models.RESTRICT,
        related_name='tickets',
        verbose_name='Покупатель'
    )
    sold = models.BooleanField(
        verbose_name='Продан',
        default=False
    )

    class Meta:
        verbose_name = 'билет'
        verbose_name_plural = 'Билеты'

    def __str__(self):
        return (self.seat_for_session.__str__()
                + ' - ' + self.customer.username)

kinescope/cinema/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Ticket, SeatForSession, Session


class TicketForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        session_id = kwargs.pop('session_ID')
        super().__init__(*args, **kwargs)
        self.fields['seat_for_session'].queryset = \
            SeatForSession.objects.filter(
                session__id=session_id,
                is_taken=False
            )

    class Meta:
        model = Ticket
        fields = ('seat_for_session',)

kinescope/cinema/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Movie, Session, Ticket
from .forms import TicketForm
from django.views.generic import TemplateView


def index(request):
    template = 'cinema/index.html'
    movies = Movie.objects.select_related('genre') \
        .filter(is_in_the_cinema=True)
    context = {
        'movies': movies,
    }
    return render(request, template, context)


def movie_detail(request, movie_id):
    current_time = timezone.now()
    movie = get_object_or_404(
        Movie,
        id=movie_id,
        is_in_the_cinema=True
    )

    sessions = movie.sessions.all().filter(
        datetime__gte=current_time
    )

    template = 'cinema/detail.html'
    context = {
        'movie': movie,
        'sessions': sessions
    }
    return render(request, template, context)


def session_list(request):
    current_time = timezone.now()
    sessions = Session.objects.all().filter(
        datetime__gte=current_time
    )

    paginator = Paginator(sessions, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    template = 'cinema/session/list.html'
    return render(request, template, context)


def session_detail(request, session_id):
    session = get_object_or_404(
        Session,
        id=session_id
    )
    available_seats = session.seats_for_session.prefetch_related('seat') \
        .filter(is_taken=False)

    template = 'cinema/session/detail.html'
    context = {
        'session': session,
        'seats_for_session': available_seats,
    }
    return render(request, template, context)


class ProfileView(TemplateView):
    template_name = 'cinema/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs['username']
        user = get_object_or_404(get_user_model(), username=username)

        tickets = user.tickets.select_related('seat_for_session')
        paginator = Paginator(tickets, 3)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'profile': user,
            'page_obj': page_obj
        }
        return context


@login_required
def tickets(request, session_id):
    session = get_object_or_404(
        Session,
        id=session_id
    )
    form = TicketForm(session_ID=session_id)
    template = 'cinema/tickets.html'
    context = {
        'session': session,
        'form': form
    }
    return render(request, template, context)


@login_required
def buy_ticket(request, session_id):
    form = TicketForm(request.POST, session_ID=session_id)
    if form.is_valid():
        ticket = form.save(commit=False)
        ticket.customer = request.user
        ticket.save()
    return redirect('cinema:profile', request.user.username)

kinescope/templates/cinema/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  {{ movie.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1 class="pb-2 mb-0">{{ movie.title }}</h1>
    <div class="row mt-3">
      <div class="col-12 col-md-6 mb-3">
        <img 
          class="img-fluid card-img-top"
          src="{{ movie.poster.url }}"
          style="object-fit: contain; height: 700px;"
        >      
      </div>  
      <div class="col mt-3">
        <div class="col-12 col-md-6">
          <h3>Жанр</h3>
          <div class="badge bg-dark text-wrap" style="width: 8rem;">
            {{ movie.genre }}
          </div>      
        </div>
        <div>
          <h3>Описание</h3>
          <h5>{{ movie.description }}</h5>      
        </div>
        <h3>Сеансы</h3>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
            {% for session in sessions %}
              <a class="btn btn-outline-dark" href="{% url 'cinema:session_detail' session.id %}" role="button">{{ session.datetime }}</a>
            {% endfor %}
        </div>  
      </div>
    </div>
  </div>
{% endblock %}

kinescope/templates/cinema/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
  Афиша
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Афиша</h1>
    <div class='row'>                        
      {% for movie in movies %}
      <div class="col-6 col-md-4 my-1">
        <div class="card">
          <img 
            class="img-fluid card-img-top"
            src="{{ movie.poster.url }}"
            style="object-fit: contain; height: 400px;"
          >
          <div class="card-body">           
            <h5 class="card-title">{{ movie.title }}</h5>
            <p class="card-text">
              Жанр: {{ movie.genre.title }}
            </p>
            <p class="card-text">
              Продолжительность: {{ movie.duration|time:"H:i" }}
            </p>
            <p class="card-text">
              {{ movie.description|truncatewords:20 }}
            </p>
            <a class="btn btn-outline-dark btn-lg" href="{% url 'cinema:movie_detail' movie.id %}" role="button">Подробнее</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>                
  </div>
{% endblock %}

kinescope/templates/cinema/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile.username }}
{% endblock %}
{% block content %}
  <div class="container pt-5">
    <h1 class="mb-5 text-center ">Страница пользователя {{ profile.username }}</h1>
    <small>
      <ul class="list-group list-group-horizontal justify-content-center mb-3">
        <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
        <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Сотрудник{% else %}Пользователь{% endif %}</li>
      </ul>
      <ul class="list-group list-group-horizontal justify-content-center">
        {% if user.is_authenticated and request.user == profile %}
        <a class="btn btn-sm btn-outline-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        {% endif %}
      </ul>
    </small>
    <br>
    <h3 class="mb-5 text-center">Билеты</h3>
    {% for ticket in page_obj %}
      <article class="mb-3">
        {% include "includes/ticket.html" %}
      </article>
    {% endfor %}
    {% include "includes/paginator.html" %}
  </div>
{% endblock %}

kinescope/templates/cinema/tickets.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Покупка билетов
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% if user.is_authenticated %}
      <div class="card" style="width: 50rem;">
        <div class="card-header">
          <h3>Купить билет</h3>
        </div>
        <div class="card-body">
          <div class="col mt-6">
            <div class="col-12 col-md-6">
              <h3>{{ session.movie }}</h3>      
            </div>
            <div class="col-12 col-md-6">
              <h5>{{ session.hall }} зал</h5>      
            </div>
            <div class="col-12 col-md-6">
              <h5>{{ session.datetime }}</h5>      
            </div>
          </div>
          <form method="post" action="{% url 'cinema:buy_ticket' session.id %}" style="width: 10rem">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="Купить" %}
          </form>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}