kinescope/cinema/urls.py
from django.urls import path
from . import views


app_name = 'cinema'

urlpatterns = [
    path('', views.index, name='index'),
    path('movies/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'sessions/<int:session_id>/',
        views.session_detail,
        name='session_detail'
    ),
    path('sessions/', views.session_list, name='session_list'),
    path('tickets/<int:session_id>/', views.tickets, name='tickets'),
    path('tickets/<int:session_id>/buy/', views.buy_ticket, name='buy_ticket'),
]

kinescope/kinescope/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_failure'

urlpatterns = [
    path('', include('cinema.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kinescope/pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),
    path('rules/', views.RulesView.as_view(), name='rules'),
]

kinescope/templates/includes/footer.html
<br>
<footer class="border-top text-center py-3">
    <p>© Кинескоп</p>    
</footer>

kinescope/templates/includes/header.html
{% load static %}
{% load django_bootstrap5 %}
{% with request.resolver_match.view_name as view_name %}
<header>
    <nav class="navbar navbar-dark" style="background-color: black">
      <div class="container">
        <a class="navbar-brand" href="{% url 'cinema:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          Кинескоп
        </a>        
        <ul class="nav  nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'cinema:index' %}active{% endif %}" href="{% url 'cinema:index' %}">
              Афиша
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'cinema:session_list' %}active{% endif %}" href="{% url 'cinema:session_list' %}">
              Сеансы
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'pages:about' %}active{% endif %}" href="{% url 'pages:about' %}">
              О кинотеатре
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:rules' %}active{% endif %}" href="{% url 'pages:rules' %}">
              Правила
            </a>
          </li>
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-light"><a class="text-decoration-none text-reset"
                  href="{% url 'cinema:profile' user.username %}">{{ user.username }}</a></button>
              <button type="button" class="btn btn-outline-light"><a class="text-decoration-none text-reset"
                  href="{% url 'logout' %}">Выйти</a></button>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-light"><a class="text-decoration-none text-reset"
                  href="{% url 'login' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-light"><a class="text-decoration-none text-reset"
                  href="{% url 'registration' %}">Регистрация</a></button>
            </div>
          {% endif %}
        </ul>      
      </div>
    </nav> 
  </header>
  {% endwith %}

kinescope/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

kinescope/templates/includes/ticket.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      <h5 class="card-title">
        {{ ticket.seat_for_session.session.movie }}
        {% if ticket.sold %}
          <span class="badge bg-success">Куплен</span>
        {% else %}
          <span class="badge bg-secondary">В обработке</span>
        {% endif %}
      </h5>
      <h6 class="card-text">
        <p>Зал: {{ ticket.seat_for_session.session.hall }}</p>
        <p>Время: {{ ticket.seat_for_session.session.datetime }}</p>
        <p>Место: {{ ticket.seat_for_session }}</p>
      </h6>
    </div>
  </div>
</div>